# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
