# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='Comments',
            field=models.TextField(blank=True, db_column='clean'),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
